
'''
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the result of the even-valued terms.
'''

def getRes(limit):
    a=0
    b=1
    result=0
    while b < limit:
        # find the next number in the Fibonacci sequence
        nextFib=a+b
        # update the lowest fib
        a=b
        # update the highest fib
        b=nextFib
        # update the sum if fib is even
        if(b % 2 == 0):        
            result+=b
        print b
    print "result:",result

# print the results. 
#getRes(10)
getRes(4000000)
